[package]
name = "abbreviator"
version = "0.1.0"
authors = ["Vagelis Prokopiou <vagelis.prokopiou@gmail.com>"]
edition = "2018"
description = "A library for abbreviating long words."
license = "MIT OR Apache-2.0"
